### ISSUE TITLE
Useful errors on incorrect post type 

### ISSUE THREAD

**Issue by Pastafarian** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#11]
Had a bit of a headache with formatting the correct post request using Angular (boundry wans't being set correctly). 

HttpContentToFormDataConverter uses the line 

```
        if (!content.IsMimeMultipartContent())
            {
                throw new Exception("Unsupported Media Type");
            }
```

To validate. 

By removing this line the 'ReadAsMultipartAsync' method validated the request and gave useful error messages. 

My suggestion would be to remove this line to ensure more useful errors are thrown.

**Comment by iLexDev** [comment]
Hi, thank you for your suggestion. I have to test it before make this change. This lines of code are present in all manuals about writing custom multipart formatter. But I also saw this error a few times  and I used regular mvc controller to validate if request is correct so if this solution allow us to have more details  about incorrectly formatted request without any negative effects I will add it to code. 

Thank you again
