### ISSUE TITLE
update nuget package

### ISSUE THREAD

**Issue by SanderMeester** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#15]
I am very happy with your project as it solves my problem rather nicely. At this point however I have to use the dll from codeproject and I would rather use a nuget package.

**Comment by Yerkon** [comment]
Hi developers! I installed from Nuget packages with version 1.1.0, which published at 2015-07-05. Can you please update it to latest version in Nuget? Thanks

**Comment by iLexDev** [comment]
Hi, sorry for long delay, I am not the author of currently present nuget package https://www.nuget.org/packages/MultipartDataMediaFormatter so I could not update it. To provide last changes of this project to nuget I created my own package - MultipartDataMediaFormatter.V2 (https://www.nuget.org/packages/MultipartDataMediaFormatter.V2) .
