### ISSUE TITLE
Support .NET Standard 2.0 ?

### ISSUE THREAD

**Issue by cipchk** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#16]
I got a warning:

```
Warning	NU1701	Package 'MultipartDataMediaFormatter.V2 2.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

**Comment by iLexDev** [comment]
I am not sure if you really need this lib if you use new asp.net core
framework. It already contains native implementation for such functionality
(like old regular asp.net mvc has).

Please let me know if you still need this for any other reason.



2017-09-06 3:19 GMT+03:00 卡色 <notifications@github.com>:

**Comment by cipchk** [comment]
gotcha, thank you again.
