### ISSUE TITLE
Problem to bind ICollection property

### ISSUE THREAD

**Issue by antobru** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#18]
Hi,

I had a problem sending data when I tried to send an array of strings that had to be inserted into a  ICollection<string> property.
I noticed that "IsGenericListOrArray" check in the FormDataToObjectConverter.cs file failed, always returning false although the property is of type ICollection.

I fixed this problem by editing the file "FormDataToObjectConverter.cs" at the line 343

`Type iListType = type.GetInterface(typeof(ICollection<>).Name);`

with

`Type iListType = type.GetInterface(typeof(ICollection<>).Name) ?? type.GetInterface(typeof(IEnumerable<>).Name);`

Now work for me! :)

I don't know if it's the correct way

**Comment by iLexDev** [comment]
Hello,

Thank you for the suggestion.
Unfortunately, this implementation may cause an error if you use string property (string is IEnumerable - tests failed with such errors).

I pushed new version (2.0.1) where you can use IEnumerable<> and IDictionary<,> as types for model's properties.

Please, let me know in case of any issues.
