### ISSUE TITLE
How to return JSON?

### ISSUE THREAD

**Issue by NZ-Jaybird** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#19]
I'm sending a multipart request from my MVC application to my Web API application and want the response to be plain JSON. Currently the response is in multipart format, how to change this?

**Comment by iLexDev** [comment]
Please send "Accept" header with value "application/json" (https://docs.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/content-negotiation)

**Comment by NZ-Jaybird** [comment]
Awesome, I was able to use the code example from that article to send back JSON without having to set the Accept header, hopefully that's not too bad practice!

I just changed the controller action to return HttpResponseMessage and used the following return statement.

```
return new HttpResponseMessage()
{
    Content = new ObjectContent<int>(attachmentId, new JsonMediaTypeFormatter())
};
```
