### ISSUE TITLE
Assembly not strong named

### ISSUE THREAD

**Issue by dberroa** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#21]
When referencing this project in a project that was signed with a strong name assembly get, this project fails to load as this project is not signed with a key.

Adding a strong name key should fix the issue. Not sure how to do this for you in terms of github, but to do it you right click the project in visual studio, select properties, then on the left is signing. Check sign the assembly and give it a name.

**Comment by dberroa** [comment]
Adding to the previous post, I did not put a password on it when I did mine. I copied through project down to add it and it worked. Would prefer your version through nuget to have it however as then I can get updates.

**Comment by iLexDev** [comment]
I uploaded the new version signed with strong name to nuget. Please let me know in case of any problems.

**Comment by dberroa** [comment]
This worked! Thank you!
