### ISSUE TITLE
This formatter makes System.Web.HttpContext.Current as null in the controller.

### ISSUE THREAD

**Issue by SnippetsUnlimited** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#26]
Just what the title says, any request that goes through this formatter makes System.Web.HttpContext.Current as null in the controller.

**Comment by iLexDev** [comment]
Could you please provide more info about the issue? I tried to reproduce it but without success.

**Comment by SnippetsUnlimited** [comment]
I cannot provide you what you are asking for.  I thought it would be easily reproducible so I mentioned here so it would help others to have a fix. As for me I moved on quickly to write my own Formatter. Here is my implementation:

`    public class MultipartFormDataMediaFormatter : JsonMediaTypeFormatter
    {
        private const string SupportedMediaType = "multipart/form-data";

        public MultipartFormDataMediaFormatter()
        {
            while (SupportedMediaTypes.Count > 0)
            {
                SupportedMediaTypes.RemoveAt(0);
            }

            SupportedMediaTypes.Add(new MediaTypeHeaderValue(SupportedMediaType));
        }

        public override bool CanReadType(Type type)
        {
            return true;
        }

        public override bool CanWriteType(Type type)
        {
            return true;
        }

        public override object ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
        {
            return GetObject(type, readStream, effectiveEncoding, formatterLogger);
        }

        private object GetObject(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
        {
            const string contentTypeHeaderName = "content-type";

            var request = HttpContext.Current.Request;
            var contentType = request.ContentType;

            var content = (HttpContent)new StreamContent(readStream);
            content.Headers.Add(contentTypeHeaderName, contentType);

            var multipart = new MultipartMemoryStreamProvider();
            var result = content.ReadAsMultipartAsync(multipart).Result;

            HttpContent jsonContent = result.Contents.FirstOrDefault(x => x.Headers.ContentDisposition.Name.Trim('\"') == ("post"));

            if (jsonContent != null)
            {
                using (var stream = new MemoryStream())
                using (var writer = new StreamWriter(stream))
                {
                    var s = jsonContent.ReadAsStringAsync().Result;
                    writer.Write(s);
                    writer.Flush();

                    stream.Position = 0;
                    return base.ReadFromStream(type, stream, effectiveEncoding, formatterLogger);
                }
            }

            return null;
        }
    }`

You would call it from client side (Angular) like:

`    const formData = new FormData();
     const data = {
        /* json body */
    }

    var postData = JSON.stringify(data);

    formData.append("post", postData);

    /* files is an array of file object from Input element of type File */
    if (files && files.length) {
      files.forEach((file) => {
        formData.append('upload', file, file.name);
      });
    }`
