### ISSUE TITLE
Publish new version to NuGet

### ISSUE THREAD

**Issue by vaindil** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#27]
Hello! Would you be able to publish a new version to NuGet? I was looking at forking this to fix empty files not working, but it turns out that was merged almost two years ago in #24.

**Comment by iLexDev** [comment]
Hello, I published new version to NuGet. Please, let me know in case of any troubles with it.

**Comment by vaindil** [comment]
Thanks for the quick reply! Looks like a dependency on Newtonsoft.Json was added with this update, is that necessary?

**Comment by iLexDev** [comment]
It is turned out that System.Net.Http is not in GAC anymore so I had to install Microsoft.AspNet.WebApi.Client nuget package and it has a dependency on Newtonsoft.Json.

**Comment by vaindil** [comment]
Ah, okay. Does the [System.Net.Http NuGet package](https://www.nuget.org/packages/System.Net.Http/) not work for this?

**Comment by iLexDev** [comment]
Actually problem is not in System.Net.Http, it is [System.Net.Http.Formatting](https://www.nuget.org/packages/System.Net.Http.Formatting) (it contains MultipartMemoryStreamProvider class)

But on its page written that it is a legacy package and System.Net.Http.Formatting is now included in the 'Microsoft.AspNet.WebApi.Client' package.

**Comment by iLexDev** [comment]
As a bonus of Newtonsoft.Json that one can write a pull request to parse json encoded keys 
 to complex properties in model (one person asked me if he can create such thing already)

**Comment by vaindil** [comment]
Ah okay, makes sense. I was just curious, thanks again!

**Comment by iLexDev** [comment]
Great, thank you for reminding me to update nuget package. )
