### ISSUE TITLE
Unable to upload file

### ISSUE THREAD

**Issue by wf-soft** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#28]
Hello, why does the request return blank once I select a file，Do I need to set anything up?

**Comment by wf-soft** [comment]
![image](https://user-images.githubusercontent.com/62228539/92592342-00e0ae00-f2d2-11ea-9854-c88b066973ea.png)
![image](https://user-images.githubusercontent.com/62228539/92592394-1655d800-f2d2-11ea-9921-ba2d5b61fad0.png)
![image](https://user-images.githubusercontent.com/62228539/92592459-2d94c580-f2d2-11ea-8e3c-09de82a65696.png)

**Comment by wf-soft** [comment]
@iLexDev

**Comment by iLexDev** [comment]
hello, no additional configurations is required.

can you please provide me your request headers ("accept" is needed to set response format) and response status code?

**Comment by wf-soft** [comment]
![image](https://user-images.githubusercontent.com/62228539/92595276-adbd2a00-f2d6-11ea-960b-e95433bbc8e4.png)

I didn't receive any response, so the program was wrong when I passed the parameters

**Comment by wf-soft** [comment]
![image](https://user-images.githubusercontent.com/62228539/92596157-fde8bc00-f2d7-11ea-97f6-1fc8d29cb3fa.png)
![image](https://user-images.githubusercontent.com/62228539/92596184-06d98d80-f2d8-11ea-809b-50b60be85c14.png)

If it's not a file, it works

**Comment by wf-soft** [comment]
I use it in Windows service Microsoft.AspNet.WebApi .SelfHost

**Comment by iLexDev** [comment]
response status code should be present even if no response body was sent

**Comment by iLexDev** [comment]
you can look at the source code tests - there is a similar example

**Comment by wf-soft** [comment]
Do you need to set file temporary storage path and so on

**Comment by wf-soft** [comment]
Hi ilexdev, I've solved this problem, it needs to choose the media type again，Thank you!

![image](https://user-images.githubusercontent.com/62228539/92633915-11ab1700-f306-11ea-957d-817e1d78b99c.png)

**Comment by iLexDev** [comment]
greate ))
