### ISSUE TITLE
It's not compatible with Asp .Net Core 3.1

### ISSUE THREAD

**Issue by mr-fedorof** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#29]
Package 'MultipartDataMediaFormatter.V2 2.0.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target 
framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

**Comment by iLexDev** [comment]
I am not sure if you really need this lib if you use asp.net core
framework. It already contains native implementation for such functionality
(like old regular asp.net mvc has).

Please let me know if you still need this for any other reason.

**Comment by mr-fedorof** [comment]
To be specific I would like to use it for HttpClient:
```C#
var HttpClient = new HttpClient();
var httpResponse = await HttpClient.GetAsync("http://localhost/content");
var data = await httpResponse.Content.ReadAsAsync<T>(/* The argument expects IEnumerable<MediaTypeFormatter> */);
```
Controllers provide model binding to bind multipart/form-data to entity.
But http clients don't support it, unfortunately: there is no MediaTypeFormatter to bind multipart/form-data to any entity.

**Comment by iLexDev** [comment]
sorry for long delay, the new version with .netstandard2.0 support is already on github and nuget
