### ISSUE TITLE
Array converter shipped with property in [property] 

### ISSUE THREAD

**Issue by andersonrocha** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#30]
The front-end of the application is sending an array in the content where the format of it comes from the 
`signatories[0][metodoAutenticacao][id]`

But the library only does the conversion if it comes in the format 
`signatory[0].metodoAutenticacao.id`

Is it possible to make this adjustment to make the reading with both dot and square brackets?

**Comment by iLexDev** [comment]
I have pushed new version with requested functionality today on github and nuget. Please take a look and let me know in case of any issues.

**Comment by andersonrocha** [comment]
Yes, it worked! Thank you very much for the speed in resolving the issue!
