### ISSUE TITLE
Problem with Nested Objects

### ISSUE THREAD

**Issue by lrosemberg** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#5]
Dear, I'm trying to upload a image and formData using AngularJS plugin ng-file-upload and your class MultipartDataMediaFormatter. 

I'm creating a complexType object.

Here is the created object:
![image](https://cloud.githubusercontent.com/assets/8175908/9233542/0c51041c-410a-11e5-89fc-7194db3196d5.png)

The JSon that I send to WebApi route is:
http://www.lrosemberg.com.br/generatedjson.txt

The data that the POST send to WebAPI is:
http://www.lrosemberg.com.br/httpdata.txt

The object SubTabelasPreco always is null, the other properties receive the value.

**Comment by iLexDev** [comment]
You should use 'dot' notation for parameters naming scheme (like ordinal ASP.NET MVC do)

Correct name for 
subTabelasPreco[0][subTabelaPrecoItens][0][ativo]

will be

subTabelasPreco[0].subTabelaPrecoItens[0].ativo
