### ISSUE TITLE
Cannot bind checkbox values to boolean

### ISSUE THREAD

**Issue by togakangaroo** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#6]
Thanks, this is a great tool

Now the issue:

Typically an `input[type=checkbox]` will transmit the string "on" or "off" when checked. It would be good for this formatter to properly convert from these to a boolean.

**Comment by iLexDev** [comment]
Hello, I am sorry for long delay.

Yes, currently formatter does not support "on off" values for binding boolean. It is pretty simple to add it but now I have no time to do this, I am sorry. As workaround you can use checkbox with value="True" (the same way as ASP.NET MVC do).
