### ISSUE TITLE
Deserializing post values of multi-select

### ISSUE THREAD

**Issue by maniacally** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#8]
I've got a form with a list of checkboxes that all have the same name and would like this to be deserialized as a List<string>.  The form is posting properly and I see the multiple values being sent, but deserialization results in a null List<string>.

I've also tried using indexes on the checkboxes as well as using a select with multiple turned on.

The closest I've come to getting it working is with indexed checkboxes where each checkbox has a name like: checkbox[0], checkbox[1], checkbox[2], etc

The problem is that only the checked ones get posted, and so when the content is deserialized into a list, the values are truncated at the first unchecked checkbox.

Example:

[x] Red
[ ] Blue
[x[ Green

Gets deserialized to a list of "Red"

But the following example:

[x] Red
[x ] Blue
[x[ Green

Gets deserialized properly a list of "Red,Blue,Green"

**Comment by iLexDev** [comment]
Hello,

In your case I would recommend to use not list of strings but list of
objects with fields like string "name" and boolean "selected". For name
field you should render hidden field with your value (like green, etc.)
For selected field you should render checbox with value "true". So in this
case you can select on a server only objects with selected value equal true.

Rendered input name example:
Prop[0].name
Prop[0].selected
...

Best regards

**Comment by maniacally** [comment]
Thanks for the quick response and suggestion.  I will give it a shot.

**Comment by maniacally** [comment]
I was able to find a solution, based on your suggestion.  I render a separate hidden input for each selected checkbox.  This way, a proper array of values (continuous,m non-sparse) is posted and properly deserialized.  Thanks again

**Comment by togakangaroo** [comment]
does this not support `<select multiple>`?

**Comment by iLexDev** [comment]
submitting form with `<select multiple>` will send to server values formatted like: `name=value1&name=value2` etc... 
This lib cannot deserialize list in this format, only sequentual indexed array is supported.
